name: Fetch Prometheus Grafana Versions

on:
  schedule:
    - cron:  '* * * * *' # Runs at 00:00, on day 1 of the month, only in January, April, July, and October.

jobs:
  fetch_promgraf_versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Latest Prometheus Version
        run: |
          PROM_V_LATEST_VERSION=$(curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
          echo ${PROM_V_LATEST_VERSION}
          PROM_LATEST_VERSION=$(echo "${PROM_V_LATEST_VERSION}" | cut -c 2-)
          echo ${PROM_LATEST_VERSION}

          sed -i " 3 c PROM_V_LATEST_VERSION=${PROM_V_LATEST_VERSION} " prometheus.sh 
          sed -i " 4 c LATEST_VERSION=${PROM_LATEST_VERSION} " prometheus.sh 

     # - name: Commit updated prometheus versions
     #   run: |
     #     git config --local user.name "GitHub Actions"
     #     git config --local user.email "actions@github.com"
     #     git add prometheus.sh   
     #    git commit -m "Update Prometheus.sh file" 
      #    git push

      - name: Fetch Latest Grafana Version
        run: |
           GRAF_V_LATEST_VERSION=$(curl -s https://api.github.com/repos/grafana/grafana/releases/latest | jq -r '.tag_name')
           echo ${GRAF_V_LATEST_VERSION}
           GRAF_LATEST_VERSION=$(echo "${GRAF_V_LATEST_VERSION}" | cut -c 2-)
           echo ${GRAF_LATEST_VERSION}

           sed -i " 5 c LATEST_VERSION=${GRAF_LATEST_VERSION} " grafana.sh

    #  - name: Commit updated grafana versions
    #    run: |
     #     git config --local user.name "GitHub Actions"
      #    git config --local user.email "actions@github.com"
      #    git add grafana.sh   
       #   git commit -m "Update Grafana.sh file" 
       #   git push

      - name: Fetch Latest Grafana Version
        run: |
           NODE_V_LATEST_VERSION=$(curl -s https://api.github.com/repos/prometheus/node_exporter/releases/latest | jq -r '.tag_name')
           echo ${NODE_V_LATEST_VERSION} 
           NODE_LATEST_VERSION=$(echo "${NODE_V_LATEST_VERSION}" | cut -c 2-)
           echo ${NODE_LATEST_VERSION}

           sed -i " 3 c NODE_V_LATEST_VERSION=${NODE_V_LATEST_VERSION} " nodeexporter.sh
           sed -i " 4 c LATEST_VERSION=${NODE_LATEST_VERSION} " nodeexporter.sh

      - name: Commit updated nodeexporter versions
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add nodeexporter.sh   
          git commit -m "Update nodeexporter.sh file" 
          git push
      
