name: Fetch Grafana Versions

on:
  schedule:
    - cron: '* * * * *' # Runs at midnight on every 10th day of the month

jobs:
  fetch_tomcat_versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Latest Grafana Version
        run: |
          PROM_V_LATEST_VERSION=$(curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
          echo ${PROM_V_LATEST_VERSION}
          PROM_LATEST_VERSION=$(echo "PROM_V_LATEST_VERSION" | cut -c 2-)
          echo ${PROM_LATEST_VERSION}

          sed -i " 3 c PROM_V_LATEST_VERSION=${PROM_V_LATEST_VERSION} " promethus.sh 
          sed -i " 4 c PROM_LATEST_VERSION=${PROM_LATEST_VERSION} " promethus.sh 

      - name: Commit updated promethus versions
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add promethus.sh
          git commit -m "Update Promethus.sh file"
          git push
